function report = run_cure_model_sanity_suite()
params = base_cure_sanity_params();
target = false(48, 48);
target(13:36, 13:36) = true;

cases = [ ...
    run_case('ideal_target_pressure', ...
    pressure_case(target, 2.25e6, 1.20e6), 0.06, params, target), ...
    run_case('below_cavitation_onset', ...
    pressure_case(target, 1.65e6, 1.20e6), 0.60, params, target), ...
    run_case('background_overpressure', ...
    pressure_case(target, 2.25e6, 2.25e6), 0.06, params, target)];

gradient_pressure = pressure_case(target, 1.85e6, 1.20e6);
gradient_pressure(target) = linspace(1.85e6, 2.25e6, nnz(target));
short_run = simulate_cure_from_pressure_map(gradient_pressure, 0.02, params, target);
long_run = simulate_cure_from_pressure_map(gradient_pressure, 0.10, params, target);

fprintf('\nCure model sanity suite\n');
fprintf('case | exposure s | IoU | coverage | over | under | dose mean ROI\n');
for idx = 1:numel(cases)
    c = cases(idx);
    fprintf('%s | %.3f | %.4f | %.1f%% | %.1f%% | %.1f%% | %.4f\n', ...
        c.name, c.exposure_time, c.IoU, c.coverage * 100, ...
        c.over * 100, c.under * 100, c.dose_roi_mean);
end
fprintf('monotonic_exposure | %.3f -> %.3f s | coverage %.1f%% -> %.1f%% | mean score %.4f -> %.4f\n', ...
    short_run.exposure_time, long_run.exposure_time, ...
    short_run.metrics.cured_coverage * 100, long_run.metrics.cured_coverage * 100, ...
    mean(short_run.cure_score(target)), mean(long_run.cure_score(target)));

report = struct();
report.cases = cases;
report.short_exposure = short_run;
report.long_exposure = long_run;
end

function case_result = run_case(name, p_amp, exposure_time, params, target)
sim = simulate_cure_from_pressure_map(p_amp, exposure_time, params, target);
case_result = struct( ...
    'name', name, ...
    'exposure_time', exposure_time, ...
    'IoU', sim.metrics.IoU, ...
    'coverage', sim.metrics.cured_coverage, ...
    'over', sim.metrics.over_cure_ratio, ...
    'under', sim.metrics.under_cure_ratio, ...
    'dose_roi_mean', mean(sim.score_components.cavitation_dose(target)));
end

function p_amp = pressure_case(target, target_pressure, background_pressure)
p_amp = ones(size(target)) .* background_pressure;
p_amp(target) = target_pressure;
end

function params = base_cure_sanity_params()
params = struct( ...
    'pressure_on', 1.72e6, ...
    'pressure_full', 1.98e6, ...
    'pressure_stream', 2.35e6, ...
    'pressure_damage', 2.80e6, ...
    'saturation_shape', 4.0, ...
    'trigger_sharpness', 3.0, ...
    'streaming_penalty_strength', 0.75, ...
    'streaming_penalty_power', 1.5, ...
    'smooth_sigma_px', 0.0, ...
    'threshold', 1.0, ...
    'cavitation_dose_time', 0.04, ...
    'thermal_weight', 0.0, ...
    'penalty_weight', 0.80, ...
    'dose_growth_floor', 0.65, ...
    'dose_trigger_weight', 0.35, ...
    'dose_cloud_radius_px', 0, ...
    'dose_cloud_floor', 1.0, ...
    'dose_cloud_weight', 0.0, ...
    'dose_seed_floor', 1.0, ...
    'dose_fill_radius_px', 0, ...
    'dose_fill_weight', 0.0);
end
