function registry = hdsp_module_registry()
%HDSP_MODULE_REGISTRY Declarative module switchboard.

registry.profiles.current_pdms_cavitation = struct( ...
    'parameters', @params_base_4p5mhz_pdms_water, ...
    'target', @target_grid_scaffold_circle_current, ...
    'phase', @phase_biasa_board_constrained_0508, ...
    'phase_board', @board_projector_error_diffusion_current, ...
    'simulation', @sim_asm_focus_scan, ...
    'exit_diagnostic', @diag_exit_field_basic, ...
    'cure', @cure_cavitation_dose_led_score_0501, ...
    'metrics', @metrics_basic_quality, ...
    'enable_exit_diagnostic', true, ...
    'enable_cure', true);

registry.profiles.a_letter_arrhenius = struct( ...
    'parameters', @params_base_4p5mhz_pdms_water, ...
    'target', @target_A_letter_edge_blur_0302, ...
    'phase', @phase_wiasa_weighted_0209, ...
    'phase_board', @board_continuous_late_round_0223, ...
    'simulation', @sim_asm_focus_scan, ...
    'exit_diagnostic', @diag_disabled, ...
    'cure', @cure_thermal_arrhenius_dose_0318, ...
    'metrics', @metrics_basic_quality, ...
    'enable_exit_diagnostic', false, ...
    'enable_cure', true);

registry.profiles.kou_early_IASA = struct( ...
    'parameters', @params_base_4p5mhz_pdms_water, ...
    'target', @target_kou_frame_0209, ...
    'phase', @phase_iasa_basic_0211, ...
    'phase_board', @board_continuous_late_round_0223, ...
    'simulation', @sim_asm_focus_scan, ...
    'exit_diagnostic', @diag_disabled, ...
    'cure', @cure_disabled, ...
    'metrics', @metrics_basic_quality, ...
    'enable_exit_diagnostic', false, ...
    'enable_cure', false);

registry.profiles.A_binary_python_handoff = struct( ...
    'parameters', @params_base_4p5mhz_pdms_water, ...
    'target', @target_A_letter_binary_0223, ...
    'phase', @phase_python_handoff_or_fallback_0315, ...
    'phase_board', @board_projector_error_diffusion_current, ...
    'simulation', @sim_asm_focus_scan, ...
    'exit_diagnostic', @diag_exit_field_basic, ...
    'cure', @cure_disabled, ...
    'metrics', @metrics_basic_quality, ...
    'enable_exit_diagnostic', true, ...
    'enable_cure', false);
end

