function registry = codex_module_registry(root_dir)
%CODEX_MODULE_REGISTRY Register intuitive module names and runnable profiles.
%
% Directory names should describe the scheme directly. For example, target
% schemes use names such as A_letter or grid_scaffold_circle_current, and
% initial-phase schemes use names such as WIASA or IASA_python_1.

if nargin < 1 || isempty(root_dir)
    root_dir = fileparts(mfilename('fullpath'));
end

p = @(varargin) fullfile(root_dir, varargin{:});

registry.root_dir = root_dir;

registry.modules.parameters.HDSP_4p5MHz_PDMS_water = p('00_parameters', 'HDSP_4p5MHz_PDMS_water');
registry.modules.target_pattern.A_letter_edge_blur_0302 = p('01_target_pattern', 'A_letter_edge_blur_0302');
registry.modules.target_pattern.grid_scaffold_circle_current = p('01_target_pattern', 'grid_scaffold_circle_current');
registry.modules.initial_phase.IASA_0211_basic = p('02_initial_phase', 'IASA_0211_basic');
registry.modules.initial_phase.IASA_python_1_focus_check = p('02_initial_phase', 'IASA_python_1_focus_check');
registry.modules.initial_phase.PANN_python_quantized_initial = p('02_initial_phase', 'PANN_python_quantized_initial');
registry.modules.phase_board.phase_to_layers_error_diffusion = p('03_phase_board', 'phase_to_layers_error_diffusion');
registry.modules.kwave_simulation.KWAVE_full_pipeline_report_snapshot = p('04_kwave_simulation', 'KWAVE_full_pipeline_report_snapshot');
registry.modules.kwave_simulation.KWAVE_full_pipeline_current = p('04_kwave_simulation', 'KWAVE_full_pipeline_current');
registry.modules.cure_prediction.cavitation.V0_trigger_activity_map = p('05_cure_prediction', 'cavitation', 'V0_trigger_activity_map');
registry.modules.cure_prediction.cavitation.V1_direct_phase_threshold = p('05_cure_prediction', 'cavitation', 'V1_direct_phase_threshold');
registry.modules.cure_prediction.cavitation.V2_cloud_consistency_dose = p('05_cure_prediction', 'cavitation', 'V2_cloud_consistency_dose');
registry.modules.cure_prediction.cavitation.V3_dose_led_score = p('05_cure_prediction', 'cavitation', 'V3_dose_led_score');
registry.modules.result_metrics.PCC_SSIM_IoU_metrics = p('06_result_metrics', 'PCC_SSIM_IoU_metrics');
registry.modules.exit_field_diagnosis.exit_complex_repair.V1_phase_board_repair = p('07_exit_field_diagnosis', 'exit_complex_repair', 'V1_phase_board_repair');
registry.modules.surrogate_model.exit_field_UNet.V1_dataset_and_train = p('08_surrogate_model', 'exit_field_UNet', 'V1_dataset_and_train');
registry.modules.integration_examples.A_letter_IASA_0211_smoke = p('09_integration_examples', 'A_letter_IASA_0211_smoke');

registry.profiles.KWAVE_full_pipeline_current = make_profile( ...
    'KWAVE_full_pipeline_current', ...
    'MATLAB', ...
    p('04_kwave_simulation', 'KWAVE_full_pipeline_current', 'HDSPdebug.m'), ...
    {registry.modules.kwave_simulation.KWAVE_full_pipeline_current}, ...
    'Current full k-Wave flow: grid scaffold target, Python initial phase, IASA refine, phase board, cavitation metrics.');

registry.profiles.KWAVE_full_pipeline_report_snapshot = make_profile( ...
    'KWAVE_full_pipeline_report_snapshot', ...
    'MATLAB', ...
    p('04_kwave_simulation', 'KWAVE_full_pipeline_report_snapshot', 'HDSPdebug.m'), ...
    {registry.modules.kwave_simulation.KWAVE_full_pipeline_report_snapshot}, ...
    'Archived full k-Wave flow used by the report snapshot.');

registry.profiles.IASA_python_1_focus_check = make_profile( ...
    'IASA_python_1_focus_check', ...
    'MATLAB', ...
    p('02_initial_phase', 'IASA_python_1_focus_check', 'IASAdebug0420.m'), ...
    {registry.modules.initial_phase.IASA_python_1_focus_check}, ...
    'Python initial phase plus IASA refinement, used for direct-phase focus checking.');

registry.profiles.A_letter_IASA_0211_smoke = make_profile( ...
    'A_letter_IASA_0211_smoke', ...
    'MATLAB', ...
    p('09_integration_examples', 'A_letter_IASA_0211_smoke', 'run_A_letter_IASA_0211_smoke.m'), ...
    {registry.modules.target_pattern.A_letter_edge_blur_0302, ...
     registry.modules.initial_phase.IASA_0211_basic, ...
     registry.modules.integration_examples.A_letter_IASA_0211_smoke}, ...
    'Small function-based smoke run: A-letter target plus 0211 padded IASA.');

registry.profiles.cavitation_V1_direct_phase_threshold = make_profile( ...
    'cavitation_V1_direct_phase_threshold', ...
    'MATLAB', ...
    p('05_cure_prediction', 'cavitation', 'V1_direct_phase_threshold', 'IASAdebug0420_cure_validation.m'), ...
    {registry.modules.cure_prediction.cavitation.V1_direct_phase_threshold}, ...
    'Direct-phase cavitation threshold validation and cure scoring.');

registry.profiles.exit_complex_repair_V1 = make_profile( ...
    'exit_complex_repair_V1', ...
    'MATLAB', ...
    p('07_exit_field_diagnosis', 'exit_complex_repair', 'V1_phase_board_repair', 'phase_board_exit_repair_validation.m'), ...
    {registry.modules.exit_field_diagnosis.exit_complex_repair.V1_phase_board_repair}, ...
    'Phase-board exit complex-field diagnosis and repair check.');

registry.profiles.exit_field_UNet_dataset_V1 = make_profile( ...
    'exit_field_UNet_dataset_V1', ...
    'MATLAB', ...
    p('08_surrogate_model', 'exit_field_UNet', 'V1_dataset_and_train', 'modulation_law_dataset_sweep.m'), ...
    {registry.modules.surrogate_model.exit_field_UNet.V1_dataset_and_train}, ...
    'Exit-field surrogate dataset sweep.');

registry.profiles.exit_field_UNet_train_V1 = make_profile( ...
    'exit_field_UNet_train_V1', ...
    'PYTHON', ...
    p('08_surrogate_model', 'exit_field_UNet', 'V1_dataset_and_train', 'train_exit_complex_unet.py'), ...
    {registry.modules.surrogate_model.exit_field_UNet.V1_dataset_and_train}, ...
    'Python U-Net training entry for exit complex-field surrogate experiments.');

end

function profile = make_profile(name, language, entry_file, module_paths, description)
profile = struct();
profile.name = name;
profile.language = language;
profile.entry_file = entry_file;
profile.module_paths = module_paths;
profile.description = description;
end
