function registry = codex_module_registry(root_dir)
%CODEX_MODULE_REGISTRY Register code-only module versions and runnable profiles.
%
% The registry keeps path selection explicit. Older HDSP scripts still carry
% their own helper calls, so each runnable profile loads one self-contained
% version directory instead of mixing helper implementations by accident.

if nargin < 1 || isempty(root_dir)
    root_dir = fileparts(mfilename('fullpath'));
end

p = @(varargin) fullfile(root_dir, varargin{:});

registry.root_dir = root_dir;

registry.modules.parameters.v1_mainline_defaults = p('00_parameters', 'v1_mainline_defaults');
registry.modules.targets.v1_hdsp_validation_target = p('01_targets', 'v1_hdsp_validation_target');
registry.modules.phase_retrieval.v1_theoretical_iasa_focus = p('02_phase_retrieval', 'v1_theoretical_iasa_focus');
registry.modules.phase_retrieval.v2_python_pann_quantized = p('02_phase_retrieval', 'v2_python_pann_quantized');
registry.modules.phase_board.v1_error_diffusion_layers = p('03_phase_board', 'v1_error_diffusion_layers');
registry.modules.kwave_modeling.v1_mainline_report_snapshot = p('04_kwave_modeling', 'v1_mainline_report_snapshot');
registry.modules.kwave_modeling.v2_mainline_current_root = p('04_kwave_modeling', 'v2_mainline_current_root');
registry.modules.cure_prediction.v1_direct_phase_cavitation = p('05_cure_prediction', 'v1_direct_phase_cavitation');
registry.modules.metrics.v1_quality_metrics = p('06_metrics', 'v1_quality_metrics');
registry.modules.exit_field_diagnostics.v1_phase_board_repair = p('07_exit_field_diagnostics', 'v1_phase_board_repair');
registry.modules.modulation_surrogate.v1_dataset_and_models = p('08_modulation_surrogate', 'v1_dataset_and_models');

registry.profiles.mainline_v1_report_snapshot = make_profile( ...
    'mainline_v1_report_snapshot', ...
    'MATLAB', ...
    p('04_kwave_modeling', 'v1_mainline_report_snapshot', 'HDSPdebug.m'), ...
    {registry.modules.kwave_modeling.v1_mainline_report_snapshot}, ...
    'Archived mainline full-flow snapshot from the report branch.');

registry.profiles.mainline_v2_current_root = make_profile( ...
    'mainline_v2_current_root', ...
    'MATLAB', ...
    p('04_kwave_modeling', 'v2_mainline_current_root', 'HDSPdebug.m'), ...
    {registry.modules.kwave_modeling.v2_mainline_current_root}, ...
    'Current root mainline snapshot moved out of the repository root.');

registry.profiles.phase_focus_v1_theoretical_iasa = make_profile( ...
    'phase_focus_v1_theoretical_iasa', ...
    'MATLAB', ...
    p('02_phase_retrieval', 'v1_theoretical_iasa_focus', 'IASAdebug0420.m'), ...
    {registry.modules.phase_retrieval.v1_theoretical_iasa_focus}, ...
    'Theoretical IASA and focal-plane validation without a physical board.');

registry.profiles.cure_v1_direct_phase = make_profile( ...
    'cure_v1_direct_phase', ...
    'MATLAB', ...
    p('05_cure_prediction', 'v1_direct_phase_cavitation', 'IASAdebug0420_cure_validation.m'), ...
    {registry.modules.cure_prediction.v1_direct_phase_cavitation}, ...
    'Direct-phase acoustic validation with cavitation-led cure scoring.');

registry.profiles.exit_field_v1_repair = make_profile( ...
    'exit_field_v1_repair', ...
    'MATLAB', ...
    p('07_exit_field_diagnostics', 'v1_phase_board_repair', 'phase_board_exit_repair_validation.m'), ...
    {registry.modules.exit_field_diagnostics.v1_phase_board_repair}, ...
    'Phase-board exit complex-field diagnosis and repair validation.');

registry.profiles.modulation_dataset_v1 = make_profile( ...
    'modulation_dataset_v1', ...
    'MATLAB', ...
    p('08_modulation_surrogate', 'v1_dataset_and_models', 'modulation_law_dataset_sweep.m'), ...
    {registry.modules.modulation_surrogate.v1_dataset_and_models}, ...
    'Modulation-law dataset sweep for exit-field surrogate exploration.');

registry.profiles.modulation_train_complex_unet_v1 = make_profile( ...
    'modulation_train_complex_unet_v1', ...
    'PYTHON', ...
    p('08_modulation_surrogate', 'v1_dataset_and_models', 'train_exit_complex_unet.py'), ...
    {registry.modules.modulation_surrogate.v1_dataset_and_models}, ...
    'Python U-Net training entry for complex exit-field surrogate experiments.');

end

function profile = make_profile(name, language, entry_file, module_paths, description)
profile = struct();
profile.name = name;
profile.language = language;
profile.entry_file = entry_file;
profile.module_paths = module_paths;
profile.description = description;
end
